// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseTable: typeof import('./src/components/BaseTable/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./src/components/Layout/src/components/footer.vue')['default']
    Heading: typeof import('./src/components/Heading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Increasing: typeof import('./src/components/Increasing.vue')['default']
    Menu: typeof import('./src/components/Menu/src/Menu.vue')['default']
    MenuItem: typeof import('./src/components/Menu/src/components/MenuItem.vue')['default']
    'MenuItem copy': typeof import('./src/components/Menu/MenuItem copy.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    Src: typeof import('./src/components/Pagination/src/index.vue')['default']
    User: typeof import('./src/components/Layout/src/user.vue')['default']
    UserInfo: typeof import('./src/components/Layout/src/components/userInfo.vue')['default']
    UserOperation: typeof import('./src/components/Layout/src/userOperation.vue')['default']
  }
}

export { }
