// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdjustConfig: typeof import('./src/components/FormMarking/src/components/AdjustConfig.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable/index.vue')['default']
    CheckboxComp: typeof import('./src/components/FormMarking/src/components/CheckboxComp.vue')['default']
    DatePicker: typeof import('./src/components/FormMarking/src/components/DatePicker.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FormComp: typeof import('./src/components/FormMarking/src/components/FormComp.vue')['default']
    FormMarkingItem: typeof import('./src/components/FormMarking/src/components/FormMarkingItem.vue')['default']
    FormMenu: typeof import('./src/components/FormMarking/src/components/FormMenu.vue')['default']
    Heading: typeof import('./src/components/Heading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Increasing: typeof import('./src/components/increasing.vue')['default']
    InputComp: typeof import('./src/components/FormMarking/src/components/InputComp.vue')['default']
    LayoutFooter: typeof import('./src/components/Layout/src/components/LayoutFooter.vue')['default']
    LayoutUserInfo: typeof import('./src/components/Layout/src/components/LayoutUserInfo.vue')['default']
    Menu: typeof import('./src/components/Menu/src/Menu.vue')['default']
    MenuItem: typeof import('./src/components/Menu/src/components/MenuItem.vue')['default']
    'MenuItem copy': typeof import('./src/components/Menu/MenuItem copy.vue')['default']
    SelectComp: typeof import('./src/components/FormMarking/src/components/SelectComp.vue')['default']
    Src: typeof import('./src/components/FormMarking/src/index.vue')['default']
  }
}

export { }
